insert into public.profiles (full_name, role, headline, bio, location, email, phone, linkedin_url, github_url) values ('Nishad K S', 'Senior Software Engineer — Full-stack', 'Senior full-stack engineer crafting reliable, high-performance web products.', 'I lead frontend and full-stack development for scalable web applications, combining reusable component systems, schema-driven forms, and product-minded engineering.', 'Kochi, Kerala, India', 'Nishadshanuz@gmail.com', '8289820945', 'https://www.linkedin.com/', 'https://github.com/') on conflict do nothing;
insert into public.skills (name, group_name, sort_order) values
('JavaScript (ES6+)', 'Languages', 1), ('TypeScript', 'Languages', 2), ('React.js', 'Frontend', 1), ('Next.js', 'Frontend', 2), ('Gatsby', 'Frontend', 3), ('Redux', 'Frontend', 4), ('Context API', 'Frontend', 5), ('Tailwind CSS', 'UI & Systems', 1), ('Material UI', 'UI & Systems', 2), ('Ant Design', 'UI & Systems', 3), ('Storybook', 'UI & Systems', 4), ('Node.js', 'Backend & Data', 1), ('Express.js', 'Backend & Data', 2), ('MongoDB', 'Backend & Data', 3), ('MySQL', 'Backend & Data', 4), ('REST APIs', 'Backend & Data', 5), ('Git', 'Tools', 1), ('AWS S3', 'Tools', 2), ('Swagger UI', 'Tools', 3), ('Jest', 'Tools', 4);
insert into public.experiences (company, title, location, start_date, end_date, summary, bullets, sort_order) values
('Feathersoft Info Solutions Ltd', 'Senior Software Engineer L3 / Senior Frontend Developer', 'Kochi', 'Sep 2020', null, 'Lead frontend development for enterprise and government projects.', ARRAY['Designed and implemented reusable, scalable UI components', 'Developed schema-driven dynamic form systems', 'Performed code reviews, optimization, and Git merge management', 'Guided junior developers and collaborated with backend teams'], 1),
('iCore Pioneer Business Solution Ltd', 'Software Engineer / Frontend Developer', 'Trivandrum', 'Aug 2019', 'Sep 2020', 'Built responsive user interfaces and reusable frontend foundations.', ARRAY['Developed responsive user interfaces using React.js', 'Created reusable components and form validations', 'Collaborated with cross-functional teams'], 2);
insert into public.projects (name, client, role, description, responsibilities, technologies, featured, sort_order) values
('Cloud Factory', 'Syngenta — US based project', 'React.js Developer', 'Enterprise DevOps platform integrating multiple AWS services into a single web application, with dynamic resource forms and dashboards.', ARRAY['Led frontend development', 'Built reusable generic UI components', 'Implemented schema-driven dynamic forms', 'Coordinated with backend teams and stakeholders'], ARRAY['React.js', 'Gatsby', 'Redux', 'Tailwind CSS', 'React Hook Form', 'AWS'], true, 1),
('All For Kids', null, 'React.js Developer', 'Telemedicine platform for pediatric clinics with appointment booking, vaccination tracking, prescriptions, invoicing, payments, and OTP authentication.', ARRAY['Structured frontend architecture', 'Developed reusable form components', 'Implemented validation and state management'], ARRAY['React.js', 'Redux', 'Node.js', 'Express', 'Razorpay'], true, 2),
('KSMART', 'Government of Kerala', 'React.js Developer', 'Government portal for civil registrations, social complaint management, and dynamic form-based workflows.', ARRAY['Led frontend development', 'Built reusable plugin-based generic components', 'Implemented Storybook for isolated component development'], ARRAY['React.js', 'Redux', 'Tailwind CSS', 'SCSS', 'Storybook'], true, 3),
('SynGPT', 'Syngenta', 'Next.js Developer', 'AI-powered chatbot and analytics platform with multi-search, token tracking, JWT authentication, and dashboard visualizations.', ARRAY['Led frontend development', 'Built reusable UI components', 'Implemented SSR and dynamic routing', 'Developed analytics dashboards'], ARRAY['Next.js', 'React.js', 'TypeScript', 'Node.js', 'React Chart'], false, 4),
('DDProperty', 'PropertyGuru', 'Next.js, Node.js Developer', 'Large-scale real estate platform supporting property sales, rentals, and advertisements across Thailand, Malaysia, and Singapore.', ARRAY['Led frontend development', 'Developed reusable components and home page widgets', 'Implemented Thai localization', 'Unit testing using Jest', 'Managed Storybook integration'], ARRAY['Next.js', 'React.js', 'TypeScript', 'Node.js', 'Storybook', 'Jest'], false, 5);
insert into public.education (degree, institution, year, sort_order) values ('B.Tech — Computer Science Engineering', 'Anna University, Chennai', '2019', 1);
insert into public.tools (name, slug, description, icon, website_url, active, sort_order) values
('React', 'react', 'Component-driven UI for fast, expressive product experiences.', '⚛', 'https://react.dev', true, 1),
('Next.js', 'nextjs', 'Full-stack React framework for production web applications.', 'N', 'https://nextjs.org', true, 2),
('Node.js', 'nodejs', 'JavaScript runtime for APIs, services, and tooling.', '⬢', 'https://nodejs.org', true, 3),
('TypeScript', 'typescript', 'Typed JavaScript for safer, scalable codebases.', 'TS', 'https://www.typescriptlang.org', true, 4),
('Supabase', 'supabase', 'Postgres, authentication, storage, and APIs for modern apps.', 'S', 'https://supabase.com', true, 5),
('Tailwind CSS', 'tailwind-css', 'Utility-first styling for consistent, responsive interfaces.', '≈', 'https://tailwindcss.com', true, 6)
on conflict (slug) do nothing;
