export type Profile = {
  id?: string;
  full_name: string;
  role: string;
  headline: string;
  bio: string;
  location: string;
  email: string;
  phone: string;
  resume_url: string | null;
  github_url: string | null;
  linkedin_url: string | null;
  avatar_url: string | null;
  available_for_work: boolean;
};

export type Skill = { id?: string; name: string; group_name: string; sort_order: number };
export type Experience = { id?: string; company: string; title: string; location: string; start_date: string; end_date: string | null; summary: string; bullets: string[]; sort_order: number };
export type Project = { id?: string; name: string; client: string | null; role: string; description: string; responsibilities: string[]; technologies: string[]; url: string | null; featured: boolean; sort_order: number };
export type ProjectVideo = { id?: string; project_id: string; title: string; description: string | null; storage_path: string; public_url: string; sort_order: number; created_at?: string };
export type Tool = { id?: string; name: string; slug: string; description: string; icon: string; website_url: string | null; active: boolean; sort_order: number; created_at?: string };
export type ToolFeature = { id?: string; tool_id: string; title: string; summary: string; details: string | null; version: string | null; release_date: string | null; source_url: string | null; sort_order: number; created_at?: string };
export type Wallpaper = { id?: string; name: string; storage_path: string; public_url: string; active: boolean; sort_order: number; created_at?: string };
export type Education = { id?: string; degree: string; institution: string; year: string; sort_order: number };
export type ContactMessage = { id: string; name: string; email: string; message: string; is_read: boolean; created_at: string };
export type InterviewQA = { question: string; answer: string };
export type InterviewPlan = { focus_areas: string[]; prepare: string[]; brush_up: string[]; likely_questions: string[]; expected_questions: InterviewQA[]; programming_questions: InterviewQA[]; preparation_steps: string[]; risk_flags: string[] };
export type JobOpportunity = { id: string; source: string; source_job_id: string; title: string; company: string; locations: string[]; work_mode: 'remote' | 'hybrid' | 'onsite' | 'unknown'; employment_type: string | null; description: string; technology_requirements: string[]; canonical_url: string; apply_url: string | null; posted_at: string | null; match_score: number; match_reason: string; interview_plan: InterviewPlan; status: 'new' | 'viewed' | 'reviewed' | 'saved' | 'applied' | 'dismissed'; fetched_at: string; };
export type CandidateResume = { id: string; file_name: string; mime_type: string; uploaded_at: string };
export type ApplicationStatus = 'applied' | 'in_progress' | 'reply_received' | 'selected' | 'rejected' | 'interview';
export type JobApplication = { id: string; job_id: string; recipient: string; subject: string; status: ApplicationStatus; sent_at: string; last_checked_at: string | null; reply_count: number; latest_reply_at: string | null; latest_reply_from: string | null; latest_reply_subject: string | null; latest_reply_snippet: string | null; gmail_thread_id: string | null; notes: string | null; job: JobOpportunity };
export type PortfolioData = { profile: Profile; skills: Skill[]; experiences: Experience[]; projects: Project[]; education: Education[]; projectVideos: ProjectVideo[]; tools: Tool[]; toolFeatures: ToolFeature[]; wallpapers: Wallpaper[] };
